name: $(date:yyyyMMdd)$(rev:.rrr)
parameters:
- name: pool_name
  displayName: Pool Name
  type: string
  default: On-Prem Production
  values:
  - "On-Prem Production"
  - "Ephemeral PROD"
trigger: none
resources:
  repositories:
    - repository: zions-ado-templates
      name: DTS/zions-ado-templates
      ref: refs/tags/v0.0.9
      type: git
extends:
  template: required-templates/dts-ci-template.yml@zions-ado-templates
  parameters:
    # Build
    build_pool_name: ${{ parameters.pool_name }}
    build_pool_demands:
    - "agent.os -equals Linux"
    - "agent.name -equals UTLXA1846-2-A6"
    build_steps:
    - template: /templates/gradle-step.yml@zions-ado-templates
      parameters:
        gradleWrapperFile: $(Build.SourcesDirectory)/gradlew
        workingDirectory: $(Build.SourcesDirectory)
        options: '-b build.gradle --no-scan --refresh-dependencies -x jib -Pcontext=release -PvaultResources=/app/Vault/resources'
        tasks: 'clean build'
        publishJUnitResults: true