name: $(date:yyyyMMdd)$(rev:.rrr)

parameters:
- name: pool_name
  displayName: Pool Name
  type: string
  default: On-Prem Production
  values:
  - On-Prem Production
  - On-Prem DR
  - Rancher - demo

resources:
  repositories:
    - repository: pipelines
      type: git
      name: DTS/devops
      ref: feature/bootstrap

trigger:
- dev/int

extends:
  template: dts-app-stack/.pipeline/ado/release-pipeline.yaml@pipelines
  parameters:
    pool_name: ${{ parameters.pool_name }}
    tb_InitialVersionPrefix: 1.0.0
    dt_crt_templatetitle_prefix: DTS/dts-app-stack/zions-re-ado-request-microservice
    dt_crt_releasetitle_prefix: zions-re-ado-request-microservice